### ISSUE TITLE
Crash: PdfSharp.Xamarin.Forms already initialized before

### ISSUE THREAD

**Issue by gannesh1996** [groege/PdfSharpCore#24]
I use PDFSharp.Xamarin.Forms in my app (Android and iOS). I initiated the package in MainActiviy.cs:

![x7ug5kh1mlzj](https://user-images.githubusercontent.com/16748886/86499189-10032700-bd8a-11ea-8c42-52355a311184.png)

This works in general, but sometimes I get a strange error which causes my app to crash:

System.InvalidOperationException: PdfSharp.Xamarin.Forms already initialized before.

This happens at random during the use of my app.

**Comment by groege** [comment]
> I use PDFSharp.Xamarin.Forms in my app (Android and iOS). I initiated the package in MainActiviy.cs:
> 
> ![x7ug5kh1mlzj](https://user-images.githubusercontent.com/16748886/86499189-10032700-bd8a-11ea-8c42-52355a311184.png)
> 
> This works in general, but sometimes I get a strange error which causes my app to crash:
> 
> System.InvalidOperationException: PdfSharp.Xamarin.Forms already initialized before.
> 
> This happens at random during the use of my app.

Seems like you use a nuget version right? I did not put it on nuget but mutliple people have forked this project and adapted it, maybe look at the nuget package, there should be a link to your version.

LG

**Comment by gannesh1996** [comment]
Correct, I use NuGet. Should I contact the owners here https://www.nuget.org/packages/PdfSharp.Xamarin.Forms/1.0.0?_src=template ?

**Comment by groege** [comment]
Yeah - just go to the project site 👍
