### ISSUE TITLE
Outdated NuGet package

### ISSUE THREAD

**Issue by jansokoly** [groege/PdfSharpCore#8]
Thanks a lot for your work on this!

I'm trying to use MigraDoc following your [Example](https://github.com/groege/PdfSharpCore/blob/master/Example/Program.cs) and using following NuGet package https://preview.nuget.org/packages/PdfSharpCore.
The NuGet package seems to be missing MigraDocCore.Rendering. Is it an "official" package, or an uncoordinated activity of someone else?

**Comment by groege** [comment]
This package is not actually done by me, sorry.
I actually have no idea how to build nuget packages.

**Comment by groege** [comment]
seems like people are forking this project without any reference to it... https://github.com/startnow65/PdfSharpCore
makes it hard to see who's doing what... sorry

**Comment by jansokoly** [comment]
No problem. Thanks anyway.
